Globals:
  # Mandatory Global Parameters to be passed to all Environments
  AppName: "MyApp"
  DeploymentAccount: "892802842344"
  DeploymentRegion: "us-east-1"
  # Global User defined Parameters to be passed to all Environments
  GlobalParam1: "GlobalParam1"
  # User defined Tags to be added to resources in all Environments
  Tags:
    AppName: "MyApp"
    AppID: "AD575KL"
    AppVersion: "1.0.0"

Environments:
  Development:
    # Mandatory Parameters to be passed to this Environment
    Name: Development
    Account: "745858611880"
    Region: "us-east-1"
    ManualApprovalStep: false
    # This Section contains optional & required User defined Parameters to deploy the Environment Stack
    BucketName: "dev-bucket"
    # User defined Tags to be added to resources in this Environment
    Tags:
      CostCenter: "D-54321"

  Production:
    # Mandatory Parameters to be passed to this Environment
    Name: Production
    Account: "948546633410"
    Region: "us-east-1"
    ManualApprovalStep: "DeployToProd"
    # This Section contains optional & required User defined Parameters to deploy the Environment Stack
    BucketName: "prod-bucket"
    # User defined Tags to be added to resources in this Environment
    Tags:
      CostCenter: "P-12345"
